# Generated by Django 5.1.1 on 2024-09-26 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_item_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user_name',
            new_name='username',
        ),
    ]
